global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'voice-ai-monitor'
    environment: 'development'

rule_files:
  - "/etc/prometheus/rules/voice_ai_rules.yml"
  - "/etc/prometheus/rules/voice-ai-agent.yml"
  - "/etc/prometheus/alerts/voice_ai_alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'voice-ai-agent'
    static_configs:
      - targets: ['voice-ai-agent:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'voice-ai-agent-health'
    static_configs:
      - targets: ['voice-ai-agent:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true